services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "33066"
    environment:
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_pass
      - MYSQL_DATABASE=apitweets
      - MYSQL_ROOT_PASSWORD=root

